version: '3.8'
services:
  grana-controle-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      RUNNING_IN_DOCKER: true
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: grana_controle
